from enum import StrEnum


class BlockerType(StrEnum):
    MISSING_PAYMENT_DOCUMENT = "MISSING_PAYMENT_DOCUMENT"
    INCORRECT_DOCUMENT_DATA = "INCORRECT_DOCUMENT_DATA"
    MISSING_ACCEPTANCE_OR_DELIVERY_CONFIRMATION = "MISSING_ACCEPTANCE_OR_DELIVERY_CONFIRMATION"
    CUSTOMER_DISPUTE = "CUSTOMER_DISPUTE"
    BROKEN_PROMISE_TO_PAY = "BROKEN_PROMISE_TO_PAY"
